export const user = [
  {
    _id: '63cbfe1a9930d4aaeb907fef',
    index: 0,
    guid: 'b2c56031-d2fd-4a46-a42d-f76f3c410dc7',
    isActive: true,
    balance: '$3,540.26',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'green',
    name: 'Kent Wood',
    gender: 'male',
    company: 'BOSTONIC',
    email: 'kentwood@bostonic.com',
    phone: '+1 (931) 499-2665',
    address: '350 Stockton Street, Sperryville, American Samoa, 1524',
    about:
      'Fugiat duis ea irure in ut incididunt magna fugiat occaecat dolor. Quis cupidatat dolore laboris quis fugiat sunt adipisicing amet culpa irure laborum amet elit elit. Eu incididunt sint laborum aute velit non dolore laborum nulla pariatur aliqua. Sit in enim ipsum veniam laboris voluptate ullamco veniam cupidatat. Dolore dolore Lorem nulla qui est dolor excepteur amet mollit nulla nisi. Do qui officia Lorem ad laborum. Officia nisi minim qui veniam veniam qui.\r\n',
    registered: '2018-05-11T07:02:21 -03:00',
    latitude: -32.797109,
    longitude: -22.163143,
    tags: ['qui', 'laborum', 'in', 'Lorem', 'est', 'et', 'ullamco'],
    friends: [
      {
        id: 0,
        name: 'Kate Patton',
      },
      {
        id: 1,
        name: 'Adriana Lancaster',
      },
      {
        id: 2,
        name: 'Gallegos Dotson',
      },
    ],
  },
  {
    _id: '63cbfe1ab26d314d0e083453',
    index: 1,
    guid: '330437d0-10f6-435a-8445-daad148b35a4',
    isActive: true,
    balance: '$2,960.18',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Doreen Kemp',
    gender: 'female',
    company: 'IPLAX',
    email: 'doreenkemp@iplax.com',
    phone: '+1 (904) 598-2964',
    address: '134 Elliott Place, Hessville, Washington, 6116',
    about:
      'Anim quis eiusmod adipisicing id laborum anim sint. Minim occaecat culpa minim eu sit sunt officia in fugiat irure ea ullamco. Magna nostrud enim consectetur do nisi anim minim aliqua exercitation non veniam in id est.\r\n',
    registered: '2019-04-26T06:55:01 -03:00',
    latitude: -0.432104,
    longitude: 22.945224,
    tags: ['in', 'elit', 'dolor', 'Lorem', 'ex', 'nostrud', 'exercitation'],
    friends: [
      {
        id: 0,
        name: 'Regina Galloway',
      },
      {
        id: 1,
        name: 'Deirdre West',
      },
      {
        id: 2,
        name: 'Lindsey Booth',
      },
    ],
  },
  {
    _id: '63cbfe1a74cfa6ba6ed46175',
    index: 2,
    guid: '178e4fa5-20e7-4757-9a51-b1b5c32b0a19',
    isActive: false,
    balance: '$3,219.68',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: 'Mcintyre Hart',
    gender: 'male',
    company: 'KNEEDLES',
    email: 'mcintyrehart@kneedles.com',
    phone: '+1 (804) 479-3452',
    address: '493 Boynton Place, Lacomb, South Carolina, 254',
    about:
      'Consequat fugiat commodo qui officia sint et reprehenderit est ea nostrud nulla et cupidatat quis. Esse ea deserunt aliquip commodo sunt minim ea et adipisicing laborum amet. Fugiat elit in laboris in ad aliquip Lorem duis fugiat consectetur irure deserunt. Voluptate occaecat est deserunt officia Lorem. Qui esse id occaecat aliqua. Deserunt ad incididunt non laboris amet adipisicing sunt nulla magna.\r\n',
    registered: '2022-02-01T02:59:46 -03:00',
    latitude: 14.896234,
    longitude: -100.89598,
    tags: [
      'Lorem',
      'velit',
      'Lorem',
      'laborum',
      'ipsum',
      'reprehenderit',
      'pariatur',
    ],
    friends: [
      {
        id: 0,
        name: 'Alvarez Bolton',
      },
      {
        id: 1,
        name: 'Alston Frank',
      },
      {
        id: 2,
        name: 'Christine Swanson',
      },
    ],
  },
  {
    _id: '63cbfe1af2d56e3def893a38',
    index: 3,
    guid: '1fa37963-68e9-4f01-96c5-3d4d327f64d8',
    isActive: true,
    balance: '$1,217.09',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'brown',
    name: 'Bauer Gillespie',
    gender: 'male',
    company: 'OVERPLEX',
    email: 'bauergillespie@overplex.com',
    phone: '+1 (963) 455-2915',
    address: '448 Lawn Court, Gila, Illinois, 4404',
    about:
      'Nisi aliquip ipsum proident anim do officia ea esse esse irure. Duis elit ex pariatur consectetur ex dolore. Aliquip Lorem minim ipsum culpa nisi cupidatat officia aute occaecat amet proident ea. Elit laborum eiusmod deserunt et sunt ullamco consectetur id ea id. Tempor anim tempor pariatur culpa sint in eiusmod aliquip cillum ipsum culpa commodo.\r\n',
    registered: '2018-01-20T05:49:16 -03:00',
    latitude: -33.921531,
    longitude: 169.650483,
    tags: [
      'aliqua',
      'proident',
      'adipisicing',
      'ullamco',
      'occaecat',
      'id',
      'eu',
    ],
    friends: [
      {
        id: 0,
        name: 'Armstrong Hawkins',
      },
      {
        id: 1,
        name: 'Conrad Coleman',
      },
      {
        id: 2,
        name: 'Linda Knox',
      },
    ],
  },
  {
    _id: '63cbfe1ad16cc86f91c3bd24',
    index: 4,
    guid: '4e845321-e97f-4a99-8b9c-080fd37b7635',
    isActive: true,
    balance: '$1,817.48',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'brown',
    name: 'Barry Morrow',
    gender: 'male',
    company: 'RAMEON',
    email: 'barrymorrow@rameon.com',
    phone: '+1 (929) 556-2081',
    address: '102 Marconi Place, Orovada, Connecticut, 4282',
    about:
      'Anim reprehenderit consequat labore proident exercitation ad aliquip laborum velit deserunt. Sit cillum veniam eu cillum esse proident culpa labore. Eu ut amet ea ullamco aliquip labore eu proident occaecat proident anim enim irure. Ex enim voluptate culpa pariatur aliqua anim ex incididunt magna amet nisi. Pariatur anim elit consequat velit sit sunt exercitation in eu ea in. Voluptate consectetur sint quis quis est anim sunt pariatur sint pariatur adipisicing enim eu proident.\r\n',
    registered: '2021-02-05T06:08:55 -03:00',
    latitude: 75.304991,
    longitude: 170.548963,
    tags: ['tempor', 'officia', 'mollit', 'velit', 'qui', 'laboris', 'elit'],
    friends: [
      {
        id: 0,
        name: 'Adela Juarez',
      },
      {
        id: 1,
        name: 'Bryant Anthony',
      },
      {
        id: 2,
        name: 'Adrian Robles',
      },
    ],
  },
];
